language: python
addons:
  apt:
    packages:
      - bash
      - wget
      - diffutils
      - make
      - git
install:
  - pip install -r requirements.txt
  - git clone https://github.com/YangModels/yang.git ../yang
script:
  - make idnits
